### PR TITLE
Fix various issues & added new documentation

### LINKED ISSUE #1: bw!botsetup not working
Hi there, 

Not sure if this repo is working but wanted to notify an error on setting up the bot.

`Error. Try bw!help (Command raised an exception: OperationalError: database is locked)`

Thanks! Let me know if I can help.

### PR DESCRIPTION
**Pull request by livkx**
- Fixes #1 - Issues with commands incl bw!botsetup, bw!bookfinished and bw!quote should be resolved.
- Updated and tidied the readme.md to provide more information as there is nothing mentioning the lack of hosted bot.
- Added a quick setup guide for self-hosting the bot.

Thanks for creating this great bot @Iqrahaq, I'm considering publicly hosting it so it's more accessible again.

### CODE REVIEW

**Comment by Iqrahaq** [comment]
Hi @livkx ,

I don't even know how to thank you. 

 I've had a quick breeze through your commits and I really appreciate the efforts you went to, to put in these fixes and changes.

I currently have some university deadlines to be dealing with but I will make sure to have a further look into your commits once I'm done with them and look to getting them merged/integrated.

Thanks again,
Iqra

**Comment by livkx** [comment]
No problem! No need to thank me, that's the beauty of open-source, it benefits everyone including me 😄 

I'm wondering, was the reason you stopped hosting the bot due to costs?

**Comment by Iqrahaq** [comment]
@livkx  The help is still very much appreciated.

And I actually stopped hosting it because I was attempting to implement some fixes but just never got around to actually implementing those fixes and bringing it back up haha.

**Comment by livkx** [comment]
I see! If you're happy with it, I'll host it then and list it publicly at some point in the near future. Feel free to add me on Discord - livkx#6969. You could consider monetisation e.g. premium features or just patreon donations!

I've just noticed the "MySQL server has gone away" bug is still occuring... I'll look into it.

**Comment by livkx** [comment]
Let's leave this a couple of days and see if it comes back up or if it's fixed now.

**Comment by livkx** [comment]
Ok @Iqrahaq - if you ignore my crazy amount of commits due to my testing workflow being terrible, pleased to say the MySQL bug is now actually fixed along with the other stuff. For every command call that connects to the database, it tests the conneciton and if it's failed it will attempt to reconnect. This way we've avoided the MySQL connection timeout if bot is inactive for a while.

**Comment by Iqrahaq** [comment]
Hi @livkx ,

Haha it was fun looking at the different notifications pop up and seeing your workflow with the commits.
And thanks for looking into the SQL side of things, I look forward to seeing the bot in action!

I'll get back to you once I've finished up my deadlines for uni (which, by my calculations, looks to be in about a month or so) and then I can look into getting your changes merged in. ;)

Speak soon!

**Review by Iqrahaq — APPROVED** [review]

**Review by Iqrahaq — APPROVED** [review]

**Review by Iqrahaq — APPROVED** [review]

**Review by Iqrahaq — APPROVED** [review]
Attempting to allow the pull request.

**Review by Iqrahaq — APPROVED** [review]
Reattempting approval of pull request.

**Comment by Iqrahaq** [comment]
Hi @livkx,

Haha, apologies for the spam you may have received. 
I'm still a little new to certain GitHub features.

I've approved and merged all the code you contributed! 
I really appreciate all your help! I want to also make sure to include a special thanks in the bot's info prompt!
And I will look into getting the bot tested and hosted!

Best,
Iqra

**Pull request merged**
